name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Deploy on every commit to main
  workflow_dispatch: # Manual trigger if you want it

permissions:
  contents: read
  pages: write # Required for GitHub Pages
  id-token: write # Required for OIDC

concurrency:
  group: pages
  cancel-in-progress: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist # CHANGE this to your build output folder

  #Set path: to your output folder
  #Plain HTML repo → .
  #Vite → dist/
  #React app → build/
  #Astro → dist/
  #Hugo → public/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
